// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kahiypfloievcktkyzps.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImthaGl5cGZsb2lldmNrdGt5enBzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0NTAzMDUsImV4cCI6MjA2ODAyNjMwNX0.DdMD_rsrbX1FkD_Qxv9jPzBeMzQJZtssfbYxKdJKsjQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});