// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Day-1 Debt fix (Story 1.1): read from env instead of hardcoding.
// See .env.example for the expected VITE_SUPABASE_* variables.
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase: ReturnType<typeof createClient<Database>> | null =
  SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY
    ? createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
        auth: {
          storage: localStorage,
          persistSession: true,
          autoRefreshToken: true,
        },
      })
    : (() => {
        console.warn(
          'VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are not set. ' +
          'Supabase features will be unavailable. ' +
          'Copy .env.example to .env and populate with your Supabase project credentials.',
        );
        return null;
      })();
